### Imports

In [1184]:
from sklearn.neural_network import MLPClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

import numpy as np
import pandas as pd

### Reading The Data

In [1120]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [1121]:
url = "/content/drive/MyDrive/roo_data.csv"
df = pd.read_csv(url)

In [1122]:
df.head()

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                        69                        63   
1                                        78                        62   
2                                        71                        86   
3                                        76                        87   
4                                        92                        62   

   Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                  78                                  87   
1                                  73                                  60   
2                                  91                                  87   
3                                  60                                  84   
4                                  90                                  67   

   Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                               94                                  94   
1                               71                                  70   
2                               61                                  81   
3                               89                                  73   
4                               71                                  89   

   Percentage in Computer Architecture  Percentage in Mathematics  \
0                                   87                         84   
1                                   73                         84   
2                                   72                         72   
3                                   62                         88   
4                                   73                         71   

   Percentage in Communication skills  Hours working per day  ...  \
0                                  61                      9  ...   
1                                  91                     12  ...   
2                                  94                     11  ...   
3                                  69                      7  ...   
4                                  73                      4  ...   

   Interested Type of Books  Salary Range Expected  In a Realtionship?  \
0              Prayer books                 salary                  no   
1                 Childrens                 salary                 yes   
2                    Travel                   Work                  no   
3                   Romance                   Work                 yes   
4                 Cookbooks                 salary                  no   

   Gentle or Tuff behaviour? Management or Technical Salary/work  \
0                   stubborn              Management      salary   
1                     gentle               Technical      salary   
2                   stubborn              Management        work   
3                     gentle              Management        work   
4                   stubborn              Management        work   

  hard/smart worker worked in teams ever? Introvert  \
0       hard worker                   yes        no   
1       hard worker                    no       yes   
2       hard worker                    no       yes   
3      smart worker                   yes       yes   
4       hard worker                   yes       yes   

               Suggested Job Role  
0              Database Developer  
1            Portal Administrator  
2            Portal Administrator  
3  Systems Security Administrator  
4        Business Systems Analyst  

[5 rows x 39 columns]

### Running The Model on Raw Data



In [1123]:
le1 = preprocessing.LabelEncoder()

datatypes = df.dtypes
df2 = df.copy()
for i in range(len(df.columns)):
  if df.dtypes[i] == "object":
    le1.fit(df2[df.columns[i]].unique())
    df2[df.columns[i]] = le1.transform(df2[df.columns[i]])

In [1124]:
df2.head()

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                        69                        63   
1                                        78                        62   
2                                        71                        86   
3                                        76                        87   
4                                        92                        62   

   Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                  78                                  87   
1                                  73                                  60   
2                                  91                                  87   
3                                  60                                  84   
4                                  90                                  67   

   Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                               94                                  94   
1                               71                                  70   
2                               61                                  81   
3                               89                                  73   
4                               71                                  89   

   Percentage in Computer Architecture  Percentage in Mathematics  \
0                                   87                         84   
1                                   73                         84   
2                                   72                         72   
3                                   62                         88   
4                                   73                         71   

   Percentage in Communication skills  Hours working per day  ...  \
0                                  61                      9  ...   
1                                  91                     12  ...   
2                                  94                     11  ...   
3                                  69                      7  ...   
4                                  73                      4  ...   

   Interested Type of Books  Salary Range Expected  In a Realtionship?  \
0                        21                      1                   0   
1                         5                      1                   1   
2                        29                      0                   0   
3                        23                      0                   1   
4                         7                      1                   0   

   Gentle or Tuff behaviour?  Management or Technical  Salary/work  \
0                          1                        0            0   
1                          0                        1            0   
2                          1                        0            1   
3                          0                        0            1   
4                          1                        0            1   

   hard/smart worker  worked in teams ever?  Introvert  Suggested Job Role  
0                  0                      1          0                   7  
1                  0                      0          1                  18  
2                  0                      0          1                  18  
3                  1                      1          1                  28  
4                  0                      1          1                   2  

[5 rows x 39 columns]

In [1125]:
y1 = df2['Suggested Job Role']
X1 = df2.drop(['Suggested Job Role'], axis = 1)
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size = 0.2)

In [1126]:
clf1 = MLPClassifier(max_iter=500, early_stopping = True, hidden_layer_sizes = (128, 64, 32), activation = "relu", solver = "adam")

In [1127]:
clf1.fit(X_train1, y_train1)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid featu

MLPClassifier(early_stopping=True, hidden_layer_sizes=(128, 64, 32),
              max_iter=500)

In [1128]:
predictions1 = clf1.predict(X_test1)
predictions_train1 = clf1.predict(X_train1)
print("Training Accuracy of Raw Data: ", accuracy_score(y_train1, predictions_train1))
print("Testing Accuracy of Raw Data: ", accuracy_score(y_test1, predictions1))

Training Accuracy of Raw Data:  0.0551875
Testing Accuracy of Raw Data:  0.05775


In [1129]:
print(classification_report(y_test1, predictions1))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       104
           1       0.00      0.00      0.00       113
           2       0.00      0.00      0.00       114
           3       0.00      0.00      0.00       104
           4       0.00      0.00      0.00       127
           5       0.00      0.00      0.00       116
           6       0.00      0.00      0.00       112
           7       0.00      0.00      0.00       119
           8       0.00      0.00      0.00       110
           9       0.00      0.00      0.00       108
          10       0.00      0.00      0.00       102
          11       0.00      0.00      0.00       102
          12       0.00      0.00      0.00       110
          13       0.00      0.00      0.00       130
          14       0.00      0.00      0.00       109
          15       0.00      0.00      0.00       131
          16       0.06      1.00      0.11       231
          17       0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [1130]:
print(confusion_matrix(y_test1, predictions1))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 2 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### Running the model with Modified Data


In [1131]:
df = pd.read_csv(url)

In [1132]:
df = df.drop(['In a Realtionship?', 'interested in games', 'Interested Type of Books','Gentle or Tuff behaviour?'], axis = 1)

In [1133]:
df['Suggested Job Role'].unique()

array(['Database Developer', 'Portal Administrator',
       'Systems Security Administrator', 'Business Systems Analyst',
       'Software Systems Engineer', 'Business Intelligence Analyst',
       'CRM Technical Developer', 'Mobile Applications Developer',
       'UX Designer', 'Quality Assurance Associate', 'Web Developer',
       'Information Security Analyst', 'CRM Business Analyst',
       'Technical Support', 'Project Manager',
       'Information Technology Manager', 'Programmer Analyst',
       'Design & UX', 'Solutions Architect', 'Systems Analyst',
       'Network Security Administrator', 'Data Architect',
       'Software Developer', 'E-Commerce Analyst',
       'Technical Services/Help Desk/Tech Support',
       'Information Technology Auditor', 'Database Manager',
       'Applications Developer', 'Database Administrator',
       'Network Engineer', 'Software Engineer', 'Technical Engineer',
       'Network Security Engineer',
       'Software Quality Assurance (QA) / Testi

In [1134]:
career_dict1 = {
    'Database Developer' : "Developer",
    'Portal Administrator' : "Administrator",
    'Systems Security Administrator' : "Administrator",
    'Business Systems Analyst' : "Analyst",
    'Software Systems Engineer' : "Developer",
    'Business Intelligence Analyst' : "Analyst",
    'CRM Technical Developer' : "Developer",
    'Mobile Applications Developer' : "Developer",
    'UX Designer' : "UI/UX Designer",
    'Quality Assurance Associate' : "Developer",
    'Web Developer' : "Developer",
    'Information Security Analyst' : "Analyst",
    'CRM Business Analyst' : "Analyst",
    'Technical Support' : "Developer",
    'Project Manager' : "Analyst",
    'Information Technology Manager' : "Analyst",
    'Programmer Analyst' : "Analyst",
    'Design & UX': "UI/UX Designer", 
    'Solutions Architect' : "DevOps Engineer",
    'Systems Analyst' : "Analyst",
    'Network Security Administrator' : "Administrator",
    'Data Architect' : "Developer",
    'Software Developer' : "Developer",
    'E-Commerce Analyst' : "Analyst",
    'Technical Services/Help Desk/Tech Support' : "Developer",
    'Information Technology Auditor' : "Engineer",
    'Database Manager' : "Analyst",
    'Applications Developer' : "Developer",
    'Database Administrator' : "Administrator" ,
    'Network Engineer' : "Developer",
    'Software Engineer' : "Developer",
    'Technical Engineer' : "Developer",
    'Network Security Engineer' : "Developer",
    'Software Quality Assurance (QA) / Testing' : "Developer", 
  }

In [1135]:
df_new1 = df.copy()
for i in df.index:
  df_new1["Suggested Job Role"][i] = career_dict1[df["Suggested Job Role"][i]]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [1136]:
df_new1["Suggested Job Role"].value_counts()

Developer          9190
Analyst            5637
Administrator      2860
UI/UX Designer     1177
DevOps Engineer     578
Engineer            558
Name: Suggested Job Role, dtype: int64

In [1137]:
le2 = preprocessing.LabelEncoder()

datatypes = df.dtypes
df3 = df_new1.copy()
for i in range(len(df.columns)):
  if df.dtypes[i] == "object":
    le2.fit(df3[df.columns[i]].unique())
    df3[df.columns[i]] = le2.transform(df3[df.columns[i]])

In [1138]:
df3.head()

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                        69                        63   
1                                        78                        62   
2                                        71                        86   
3                                        76                        87   
4                                        92                        62   

   Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                  78                                  87   
1                                  73                                  60   
2                                  91                                  87   
3                                  60                                  84   
4                                  90                                  67   

   Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                               94                                  94   
1                               71                                  70   
2                               61                                  81   
3                               89                                  73   
4                               71                                  89   

   Percentage in Computer Architecture  Percentage in Mathematics  \
0                                   87                         84   
1                                   73                         84   
2                                   72                         72   
3                                   62                         88   
4                                   73                         71   

   Percentage in Communication skills  Hours working per day  ...  \
0                                  61                      9  ...   
1                                  91                     12  ...   
2                                  94                     11  ...   
3                                  69                      7  ...   
4                                  73                      4  ...   

   Job/Higher Studies?  Type of company want to settle in?  \
0                    0                                   8   
1                    1                                   4   
2                    0                                   5   
3                    0                                   7   
4                    0                                   9   

   Taken inputs from seniors or elders  Salary Range Expected  \
0                                    0                      1   
1                                    1                      1   
2                                    1                      0   
3                                    0                      0   
4                                    0                      1   

   Management or Technical  Salary/work  hard/smart worker  \
0                        0            0                  0   
1                        1            0                  0   
2                        0            1                  0   
3                        0            1                  1   
4                        0            1                  0   

   worked in teams ever?  Introvert  Suggested Job Role  
0                      1          0                   3  
1                      0          1                   0  
2                      0          1                   0  
3                      1          1                   0  
4                      1          1                   1  

[5 rows x 35 columns]

In [1139]:
#80-20 split
y2 = df3['Suggested Job Role']
X2 = df3.drop(['Suggested Job Role'], axis = 1)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size = 0.2)

In [1140]:
clf2 = MLPClassifier(max_iter=500, early_stopping = True, hidden_layer_sizes = (128, 64, 32), activation = "relu", solver = "adam")

In [1141]:
clf2.fit(X_train2, y_train2)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid featu

MLPClassifier(early_stopping=True, hidden_layer_sizes=(128, 64, 32),
              max_iter=500)

In [1142]:
predictions2 = clf2.predict(X_test2)
predictions_train2 = clf2.predict(X_train2)
print("Training Accuracy with Modified Data (80-20 split): ", accuracy_score(y_train2, predictions_train2))
print("Testing Accuracy with Modified Data (80-20 split): ", accuracy_score(y_test2, predictions2))

Training Accuracy with Modified Data (80-20 split):  0.461875
Testing Accuracy with Modified Data (80-20 split):  0.4465


In [1143]:
print(classification_report(y_test2, predictions2))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       611
           1       0.14      0.00      0.00      1144
           2       0.00      0.00      0.00       115
           3       0.45      1.00      0.62      1791
           4       0.00      0.00      0.00       108
           5       0.00      0.00      0.00       231

    accuracy                           0.45      4000
   macro avg       0.10      0.17      0.10      4000
weighted avg       0.24      0.45      0.28      4000



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [1144]:
print(confusion_matrix(y_test2, predictions2))

[[   0    0    0  611    0    0]
 [   0    1    0 1143    0    0]
 [   0    0    0  115    0    0]
 [   0    6    0 1785    0    0]
 [   0    0    0  108    0    0]
 [   0    0    0  231    0    0]]


In [1145]:
#70-30 split
y2 = df3['Suggested Job Role']
X2 = df3.drop(['Suggested Job Role'], axis = 1)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size = 0.3)

In [1146]:
clf2 = MLPClassifier(max_iter=500, early_stopping = True, hidden_layer_sizes = (128, 64, 32), activation = "relu", solver = "adam")

In [1147]:
clf2.fit(X_train2, y_train2)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid featu

MLPClassifier(early_stopping=True, hidden_layer_sizes=(128, 64, 32),
              max_iter=500)

In [1148]:
predictions2 = clf2.predict(X_test2)
predictions_train2 = clf2.predict(X_train2)
print("Training Accuracy with Modified Data (70-30 split): ", accuracy_score(y_train2, predictions_train2))
print("Testing Accuracy with Modified Data (70-30 split): ", accuracy_score(y_test2, predictions2))

Training Accuracy with Modified Data (70-30 split):  0.4615
Testing Accuracy with Modified Data (70-30 split):  0.453


In [1149]:
print(classification_report(y_test2, predictions2))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       830
           1       0.22      0.00      0.01      1730
           2       0.00      0.00      0.00       196
           3       0.45      0.99      0.62      2727
           4       0.00      0.00      0.00       168
           5       0.00      0.00      0.00       349

    accuracy                           0.45      6000
   macro avg       0.11      0.17      0.11      6000
weighted avg       0.27      0.45      0.29      6000



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [1150]:
print(confusion_matrix(y_test2, predictions2))

[[   0    4    0  826    0    0]
 [   0    8    0 1722    0    0]
 [   0    3    0  193    0    0]
 [   0   17    0 2710    0    0]
 [   0    2    0  166    0    0]
 [   0    3    0  346    0    0]]


In [1151]:
#60-40 split
y2 = df3['Suggested Job Role']
X2 = df3.drop(['Suggested Job Role'], axis = 1)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size = 0.4)

In [1152]:
clf2 = MLPClassifier(max_iter=500, early_stopping = True, hidden_layer_sizes = (128, 64, 32), activation = "relu", solver = "adam")

In [1153]:
clf2.fit(X_train2, y_train2)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid featu

MLPClassifier(early_stopping=True, hidden_layer_sizes=(128, 64, 32),
              max_iter=500)

In [1154]:
predictions2 = clf2.predict(X_test2)
predictions_train2 = clf2.predict(X_train2)
print("Training Accuracy with Modified Data (60-40 split): ", accuracy_score(y_train2, predictions_train2))
print("Testing Accuracy with Modified Data (60-40 split): ", accuracy_score(y_test2, predictions2))

Training Accuracy with Modified Data (60-40 split):  0.45841666666666664
Testing Accuracy with Modified Data (60-40 split):  0.45575


In [1155]:
print(classification_report(y_test2, predictions2))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1156
           1       0.21      0.01      0.01      2238
           2       0.00      0.00      0.00       239
           3       0.46      0.99      0.63      3674
           4       0.00      0.00      0.00       223
           5       0.00      0.00      0.00       470

    accuracy                           0.46      8000
   macro avg       0.11      0.17      0.11      8000
weighted avg       0.27      0.46      0.29      8000



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [1156]:
print(confusion_matrix(y_test2, predictions2))

[[   0   13    0 1143    0    0]
 [   0   17    0 2221    0    0]
 [   0    1    0  238    0    0]
 [   0   45    0 3629    0    0]
 [   0    0    0  223    0    0]
 [   0    5    0  465    0    0]]


### Running the model with Correlated Data from Assignment 1

In [1157]:
url = "/content/drive/MyDrive/roo_data.csv"
df = pd.read_csv(url)

In [1158]:
df = df.drop(['In a Realtionship?', 'interested in games', 'Interested Type of Books','Gentle or Tuff behaviour?'], axis = 1)

In [1159]:
df['interested career area '].value_counts()

testing                     3354
system developer            3349
cloud computing             3343
security                    3328
Business process analyst    3321
developer                   3305
Name: interested career area , dtype: int64

In [1160]:
df["Interested subjects"].value_counts()

networks                 2096
IOT                      2037
data engineering         2025
Computer Architecture    2010
hacking                  2008
programming              2007
cloud computing          1993
Software Engineering     1949
Management               1938
parallel computing       1937
Name: Interested subjects, dtype: int64

In [1161]:
career_dict2 = {
    "networks" : { 
        "testing" : "Networks Engineer",                     
        "system developer" : "Developer",            
        "cloud computing" : "Cloud Engineer",             
        "security" : "Networks Engineer",                    
        "Business process analyst" : "Analyst",    
        "developer" : "Networks Engineer"
    },                 
    "IOT" : { 
        "testing" : "Developer",                      
        "system developer" : "Developer",            
        "cloud computing" : "Cloud Engineer",             
        "security" : "Security Engineer",                    
        "Business process analyst" : "Analyst",   
        "developer" : "Networks Engineer"
    },                      
    "data engineering" : { 
        "testing" : "Data Engineer",                     
        "system developer" : "Developer",             
        "cloud computing" : "Data Engineer",             
        "security" : "Security Engineer",                    
        "Business process analyst" : "Analyst",    
        "developer" : "Data Engineer"
    },         
    "Computer Architecture" : { 
        "testing" : "Developer",                      
        "system developer" : "Developer",            
        "cloud computing" : "Developer",             
        "security" : "Security Engineer",                    
        "Business process analyst" : "Analyst",    
        "developer" : "Developer"
    },    
    "hacking" : { 
        "testing" : "Security Engineer",                     
        "system developer" : "Security Engineer",            
        "cloud computing" : "Cloud Engineer",             
        "security" : "Security Engineer",                    
        "Business process analyst" : "Analyst",    
        "developer" : "Security Engineer"
    },                  
    "programming" : { 
        "testing" : "Developer",                     
        "system developer" : "Developer",            
        "cloud computing" : "Developer",             
        "security" : "Security Engineer",                    
        "Business process analyst" : "Analyst",    
        "developer" : "Developer"
    },              
    "cloud computing" : { 
        "testing" : "Cloud Engineer",                     
        "system developer" : "Cloud Engineer",            
        "cloud computing" : "Cloud Engineer",            
        "security" : "Security Engineer",                    
        "Business process analyst" : "Analyst",    
        "developer" : "Cloud Engineer"
    },          
    "Software Engineering" : { 
        "testing" : "Developer",                     
        "system developer" : "Developer",            
        "cloud computing" : "Developer",             
        "security" : "Security Engineer",                    
        "Business process analyst" : "Analyst",    
        "developer" : "Developer"
    },     
    "Management" : { 
        "testing" : "Analyst",                     
        "system developer" : "Developer",            
        "cloud computing" : "Analyst",             
        "security" : "Security Engineer",                    
        "Business process analyst" : "Analyst",    
        "developer" : "Developer"
    },               
    "parallel computing" : { 
        "testing" : "Developer",                    
        "system developer" : "Networks Engineer",            
        "cloud computing" : "Developer",             
        "security" : "Security Engineer",                    
        "Business process analyst" : "Analyst",    
        "developer" : "Developer"
    }       
}


In [1162]:
df_new2 = df.copy()
for i in df.index:
  df_new2["Suggested Job Role"][i] = career_dict2[df["Interested subjects"][i]][df["interested career area "][i]]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [1163]:
df_new2["Suggested Job Role"].value_counts()

Developer            6984
Security Engineer    3979
Analyst              3978
Cloud Engineer       2357
Networks Engineer    1707
Data Engineer         995
Name: Suggested Job Role, dtype: int64

In [1164]:
le3 = preprocessing.LabelEncoder()

datatypes = df.dtypes
df4 = df_new2.copy()
for i in range(len(df.columns)):
  if df.dtypes[i] == "object":
    le3.fit(df4[df.columns[i]].unique())
    df4[df.columns[i]] = le3.transform(df4[df.columns[i]])

In [1165]:
df4.head()

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                        69                        63   
1                                        78                        62   
2                                        71                        86   
3                                        76                        87   
4                                        92                        62   

   Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                  78                                  87   
1                                  73                                  60   
2                                  91                                  87   
3                                  60                                  84   
4                                  90                                  67   

   Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                               94                                  94   
1                               71                                  70   
2                               61                                  81   
3                               89                                  73   
4                               71                                  89   

   Percentage in Computer Architecture  Percentage in Mathematics  \
0                                   87                         84   
1                                   73                         84   
2                                   72                         72   
3                                   62                         88   
4                                   73                         71   

   Percentage in Communication skills  Hours working per day  ...  \
0                                  61                      9  ...   
1                                  91                     12  ...   
2                                  94                     11  ...   
3                                  69                      7  ...   
4                                  73                      4  ...   

   Job/Higher Studies?  Type of company want to settle in?  \
0                    0                                   8   
1                    1                                   4   
2                    0                                   5   
3                    0                                   7   
4                    0                                   9   

   Taken inputs from seniors or elders  Salary Range Expected  \
0                                    0                      1   
1                                    1                      1   
2                                    1                      0   
3                                    0                      0   
4                                    0                      1   

   Management or Technical  Salary/work  hard/smart worker  \
0                        0            0                  0   
1                        1            0                  0   
2                        0            1                  0   
3                        0            1                  1   
4                        0            1                  0   

   worked in teams ever?  Introvert  Suggested Job Role  
0                      1          0                   1  
1                      0          1                   0  
2                      0          1                   5  
3                      1          1                   4  
4                      1          1                   3  

[5 rows x 35 columns]

In [1166]:
#80-20 split
y3 = df4['Suggested Job Role']
X3 = df4.drop(['Suggested Job Role'], axis = 1)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size = 0.2)

In [1167]:
clf3 = MLPClassifier(max_iter=500, early_stopping = True, hidden_layer_sizes = (128, 64, 32), activation = "relu", solver = "adam")

In [1168]:
clf3.fit(X_train3, y_train3)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid featu

MLPClassifier(early_stopping=True, hidden_layer_sizes=(128, 64, 32),
              max_iter=500)

In [1169]:
predictions3 = clf3.predict(X_test3)
predictions_train3 = clf3.predict(X_train3)
print("Training Accuracy of Correlated Data from Assigment 1 (80-20 split): ", accuracy_score(y_train3, predictions_train3))
print("Testing Accuracy of Correlated Data from Assigment 1 (80-20 split): ", accuracy_score(y_test3, predictions3))

Training Accuracy of Correlated Data from Assigment 1 (80-20 split):  0.9929375
Testing Accuracy of Correlated Data from Assigment 1 (80-20 split):  0.99


In [1170]:
print(classification_report(y_test3, predictions3))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       787
           1       0.98      0.99      0.99       496
           2       0.99      0.98      0.99       186
           3       0.99      0.99      0.99      1373
           4       0.97      0.99      0.97       336
           5       0.99      0.99      0.99       822

    accuracy                           0.99      4000
   macro avg       0.99      0.99      0.99      4000
weighted avg       0.99      0.99      0.99      4000



In [1171]:
print(confusion_matrix(y_test3, predictions3))

[[ 787    0    0    0    0    0]
 [   0  492    1    3    0    0]
 [   0    2  182    0    0    2]
 [   2    7    0 1354    6    4]
 [   0    0    0    4  331    1]
 [   0    0    0    2    6  814]]


In [1172]:
#70-30 split
y3 = df4['Suggested Job Role']
X3 = df4.drop(['Suggested Job Role'], axis = 1)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size = 0.3)

In [1173]:
clf3 = MLPClassifier(max_iter=500, early_stopping = True, hidden_layer_sizes = (128, 64, 32), activation = "relu", solver = "adam")

In [1174]:
clf3.fit(X_train3, y_train3)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid featu

MLPClassifier(early_stopping=True, hidden_layer_sizes=(128, 64, 32),
              max_iter=500)

In [1175]:
predictions3 = clf3.predict(X_test3)
predictions_train3 = clf3.predict(X_train3)
print("Training Accuracy of Correlated Data from Assigment 1 (70-30 split): ", accuracy_score(y_train3, predictions_train3))
print("Testing Accuracy of Correlated Data from Assigment 1 (70-30 split): ", accuracy_score(y_test3, predictions3))

Training Accuracy of Correlated Data from Assigment 1 (70-30 split):  0.9928571428571429
Testing Accuracy of Correlated Data from Assigment 1 (70-30 split):  0.9891666666666666


In [1176]:
print(classification_report(y_test3, predictions3))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1213
           1       0.98      0.99      0.99       692
           2       0.98      1.00      0.99       297
           3       1.00      0.99      0.99      2067
           4       0.96      0.97      0.97       519
           5       0.99      0.98      0.98      1212

    accuracy                           0.99      6000
   macro avg       0.98      0.99      0.99      6000
weighted avg       0.99      0.99      0.99      6000



In [1177]:
print(confusion_matrix(y_test3, predictions3))

[[1213    0    0    0    0    0]
 [   0  686    4    2    0    0]
 [   0    0  296    0    0    1]
 [   0   11    0 2042    3   11]
 [   0    0    0    7  506    6]
 [   0    0    2    0   18 1192]]


In [1178]:
#60-40 split
y3 = df4['Suggested Job Role']
X3 = df4.drop(['Suggested Job Role'], axis = 1)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size = 0.4)

In [1179]:
clf3 = MLPClassifier(max_iter=500, early_stopping = True, hidden_layer_sizes = (128, 64, 32), activation = "relu", solver = "adam")

In [1180]:
clf3.fit(X_train3, y_train3)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid featu

MLPClassifier(early_stopping=True, hidden_layer_sizes=(128, 64, 32),
              max_iter=500)

In [1181]:
predictions3 = clf3.predict(X_test3)
predictions_train3 = clf3.predict(X_train3)
print("Training Accuracy of Correlated Data from Assigment 1 (60-40 split): ", accuracy_score(y_train3, predictions_train3))
print("Testing Accuracy of Correlated Data from Assigment 1 (60-40 split): ", accuracy_score(y_test3, predictions3))

Training Accuracy of Correlated Data from Assigment 1 (60-40 split):  0.9909166666666667
Testing Accuracy of Correlated Data from Assigment 1 (60-40 split):  0.9865


In [1182]:
print(classification_report(y_test3, predictions3))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1558
           1       0.98      0.99      0.98       917
           2       0.96      0.97      0.96       418
           3       0.98      0.99      0.99      2832
           4       0.99      0.98      0.98       655
           5       0.99      0.97      0.98      1620

    accuracy                           0.99      8000
   macro avg       0.98      0.98      0.98      8000
weighted avg       0.99      0.99      0.99      8000



In [1183]:
print(confusion_matrix(y_test3, predictions3))

[[1558    0    0    0    0    0]
 [   0  906    0   11    0    0]
 [   0    2  404    0    0   12]
 [   0   16    0 2811    1    4]
 [   0    0    0   12  639    4]
 [   0    0   19   22    5 1574]]
